openapi: 3.0.1
info:
  title: tkm-ms-test-utility
  description: "RESTful APIs provided for test utility"
  version: '1.2.1'
servers:
  - url: http://localhost:2000/tkm-ms-test-utility
tags:
  - name: authenticated
    description: exposed via APIM
  - name: restricted
    description: only for internal use
paths:
